#!/bin/bash

# Check if the script was called with the correct number of arguments
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 username group"
    exit 1
fi

# Add the user to the group
username=$1
group=$2
usermod -a -G $group $username

echo "User $username
